services:
  mysql:
    image: mysql:latest
    container_name: edufor_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edufor
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: edufor_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  redis_data:
